name: comics_center
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  infinite_scroll_pagination: ^3.2.0
  flutter_dotenv: ^5.0.2
  dio: ^5.1.2
  crypto: ^3.0.3
  go_router: ^8.0.5
  flutter_local_notifications: ^14.1.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  path: ^1.8.2
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
     - .env
     - assets/images/

  fonts:
     - family: Bangers
       fonts:
         - asset: fonts/Bangers-Regular.ttf

